name: Build & lint project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install frontend dependencies
        run: cd web/themes/imalabya && yarn install
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
      - name: Run PHPCS with DrupalPractice on modules
        uses: docker://hussainweb/drupalqa:php7.4
        with:
          args: phpcs --standard="Drupal,DrupalPractice" -n --extensions="php,module,install,theme" web/themes/imalabya web/modules/custom --ignore=web/themes/*/dist/,web/themes/*/Gulpfile.js,web/themes/*/node_modules/
